INSERT INTO users (USER_ID, EMAIL, CREATED_AT, BIRTHDAY, FIRST_NAME, PASSWORD) VALUES(1, 'admin@keyless.com', CURRENT_TIMESTAMP, '2016-01-01', 'admin', 'admin')
INSERT INTO users (USER_ID, EMAIL, CREATED_AT, BIRTHDAY, FIRST_NAME, PASSWORD) VALUES(2, 'dave@keyless.com', CURRENT_TIMESTAMP, '2016-01-01', 'dave', 'dave')
INSERT INTO users (USER_ID, EMAIL, CREATED_AT, BIRTHDAY, FIRST_NAME, PASSWORD) VALUES(3, 'mani@keyless.com', CURRENT_TIMESTAMP, '2016-01-01', 'mani', 'mani')
INSERT INTO users (USER_ID, EMAIL, CREATED_AT, BIRTHDAY, FIRST_NAME, PASSWORD) VALUES(4, 'lukas@keyless.com', CURRENT_TIMESTAMP, '2016-01-01', 'lukas', 'lukas')

INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID, KEYNAME) VALUES (1, '11', 1, 'Key1')
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID, KEYNAME) VALUES (2, '12', 2, 'Key2')
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID, KEYNAME) VALUES (3, '13', 3, 'Key3')
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID, KEYNAME) VALUES (4, '14', 4, 'Key4')
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID, KEYNAME) VALUES (5, '15', 1, 'Key5')
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID, KEYNAME) VALUES (6, '16', 2, 'Key6')
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID, KEYNAME) VALUES (7, '17', 3, 'Key7')
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID, KEYNAME) VALUES (8, '18', 4, 'Key8')

INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (1, 'Now: This is a test log-entry.')
INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (2, 'Now: This is the second test log-entry.')
INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (3, 'Now: This is the third test log-entry.')
INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (4, 'Now: This is the fourth test log-entry.')
INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (5, 'Now: This is the fifth test log-entry.')