INSERT INTO users (USER_ID, EMAIL, CREATED_AT, BIRTHDAY, FIRST_NAME, PASSWORD) VALUES(1, 'admin@keyless.com', CURRENT_TIMESTAMP, '2016-01-01', 'admin', 'admin')
INSERT INTO users (USER_ID, EMAIL, CREATED_AT, BIRTHDAY, FIRST_NAME, PASSWORD) VALUES(2, 'dave@keyless.com', CURRENT_TIMESTAMP, '2016-01-01', 'dave', 'dave')
INSERT INTO users (USER_ID, EMAIL, CREATED_AT, BIRTHDAY, FIRST_NAME, PASSWORD) VALUES(3, 'mani@keyless.com', CURRENT_TIMESTAMP, '2016-01-01', 'mani', 'mani')
INSERT INTO users (USER_ID, EMAIL, CREATED_AT, BIRTHDAY, FIRST_NAME, PASSWORD) VALUES(4, 'lukas@keyless.com', CURRENT_TIMESTAMP, '2016-01-01', 'lukas', 'lukas')

INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID) VALUES (1, 10, 1)
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID) VALUES (2, 11, 2)
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID) VALUES (3, 12, 3)
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID) VALUES (4, 13, 4)
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID) VALUES (5, 14, 1)
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID) VALUES (6, 15, 2)
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID) VALUES (7, 16, 3)
INSERT INTO lock_keys (KEY_ID, AID, OWNER_USER_ID) VALUES (8, 17, 4)

INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (1, 'Now: This is a test log-entry.')
INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (2, 'Now: This is the second test log-entry.')
INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (3, 'Now: This is the third test log-entry.')
INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (4, 'Now: This is the fourth test log-entry.')
INSERT into system_log (SYSTEM_LOG_ID, EVENT) VALUES (5, 'Now: This is the fifth test log-entry.')